trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

pr: none

resources:
  repositories:
    - repository: templates
      type: github
      name: negiranbir109/mvp
      ref: main
      endpoint: 'testconnect'

jobs:
  - template: templates/build.yml@templates
    parameters:
      publish_artifact_contents: |
        .terraform.lock.hcl
        *.tf
        environments/**