trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

pr: none

resources:
  repositories:
    - repository: templates
      type: github
      name: negiranbir109/mvp
      ref: main
      endpoint: 'github.com_negiranbir109'
